[gcp_service_account]
type = "service_account"
project_id = "soy-braid-387011"
private_key_id = "21ed336a78345ac6b00123f2f2cf3ad948735f05"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDJPLMJ12qMwrpl
QASLOGY0QsPdRk9TFuhss2JZOzpzDKS/xBu6lCGIhfUYs1+f+EZdyOnRohguJxtD
UErrJd9tTs9dvkAN1NTVKr+bps1VY5UFCoI1vLhi41/rOrt9eIH9ukDTPoDltQX/
hcUGX95BPiRCANJGRd4PV+FQQm+pir64qPW/h2Jw6S+RQwOWyECDhj+vRPVcv41u
hinq/LEgoDMT7XpafKp5Pns/X1aXey4ScNyQ/+LAcI7427MlrRZz7dR2fmgA/u7i
OisNBXL8824JHeSmH2IoLiNDvfvQ0ym2OrhsvVSQrC/FM97ZBM0w5wREa+fglf4i
nGGsbzWPAgMBAAECggEAQ+INdT7tCvGvRfNr9PjABVYWU0DiBmHeYri6buZbZ672
rle9kNliXHbvwHbVxZVPS1i4g0ZeSMdZW4Is25jpfyqMKg/A9Ml8SDJE84E3l9vh
S5OJbA4u1vDjjOrBj2hE1W3sazYU7if8D3+1AFr7kt+fBILZa+oqp9tZvqTCnRp+
E4hdoDxOTofEckxU3ALpDVGlGHqw7F+6Bi5Qa9O6+9HoHm4AxGbCz8EEpCaK6erJ
UYKM7pxhIG32noL1gcabq2KDJgK2FO+nFeeirAIzFPVF+R2sBrMchFS8hdQYKwAy
VRBuKeiqUz+BTk/fHMv7M/Jedga1I44jThETAZ4vRQKBgQD8LhJDtx9q5Iv6wgi/
252r4KhEtzicRW6UiAZnzku4S06cD8mWYPOKRzE2K+xgo0JJ67auEwVS+kmTdMwZ
q2gJv2PBw2qGmtVqwvv6BmxEX2pQME5JVBvdpffKLBnA3AjlUHXyHpNUl3xqiNys
F6S3EMPZR+dAejaf58eBSq7B7QKBgQDMSROjsiYtDHzapgeAtknCKNHZ/QBFfFqb
mmkCMuBb0RB9NOylm26m5C+BtKwWv5b91+e8tRJd7N+/t9nA2hjMUl0mHlk8irSK
7idX/XUmit1pkv0u3xU0Bie5dWJgSc936zMNUfhR5r3yRYbxTHh3uIPO299xecD+
OC/dIC3V6wKBgQD5Xvmyupg31O9TNaL/TkX5nDvpT6GMbuBtwqFK72ZTRSzkCHyY
1yCdoc7ZOdASs/6uKIhKVQbTyisNxNa7n5NO6FLWXc6uctgOLeiMkuNnLU9tIoeX
3bN8mE2TP87rtuqZENrBZVjdsrtWgiZtiyfX250/9OmKChCQSdwwT1DG9QKBgC2R
o4Lha2ijH3q6jHPmtb9M0brZl+ToH2IUaJYn+SoiEZaMZrluWZl6zyoUvkp4xFqt
fbD3hzhSbXrbrQQ64ks5mDO3k1pQ6oMPKtGS5T4Kvecd9cIt2xH2yYeyKpamAFSU
r5eqEEVcvkQ7xCUxVLIIA8bx/v7WFPngWLTvx6mvAoGBAPapJEnfNAXNs2A+n5RP
GEDss18DZt1zK09X1kGR/qg4mI+daExl8Po995WHOXtZrHyga1uQxz/ezqZ3EFMT
8fvYafTLK+tJUaTm5ZU419R6bPXVX6p9a31lqsT78T8Sbf5O3Ny1n4jwNkE0RVT/
zA3j46R52jtOcPlvd2RBXPlr
-----END PRIVATE KEY-----
"""
client_email = "vergo-report-generator@soy-braid-387011.iam.gserviceaccount.com"
client_id = "104966454109275277449"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/vergo-report-generator%40soy-braid-387011.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
